var config = {
    AUTH_KEY: 'IGQVJVOXJnSHBKb0VKSzUyRXBzSUV1OGgzaUpnNGNLVWFTejR0cmppTUR3QnBDdndHRURQY3ZA6OUhPVzUtUEd5MTIzbmE3b0cyTElIVWEwMGI5c2NEVkIybEF1VGRrNXBsd2ppYUdYN3dPS2ZAQTEw1dgZDZD',
    GOOGLE_API: 'AIzaSyCU_pwpwrZB-U5qf3xxtHG-06TzAKmabVE'
}
